### PR TITLE
Adding the missing functions for Randomness

### PR DESCRIPTION
**Pull request by uwieder**
Adding the wrapper for more functions in Randomness API

### CODE REVIEW

**Comment by uwieder** [comment]
By thread-safe do you mean remove the static getInstance method so that it is created normally via the constructor?

**Comment by mbudiu-vmw** [comment]
Yes.
I think that if you pretty much remove the static it should work.

**Comment by uwieder** [comment]
I don't think so. If I make it non static the getInstance() method cannot be called. I need to remove it completely and then change all the places where getInstance() is called with a standard constructor now?

**Comment by mbudiu-vmw** [comment]
Or you can have getInstance just call a constructor and return the result.
But probably you are right.

**Comment by uwieder** [comment]
I changed all the places where Randomness is called. **The NextKSketch test now fails!**
This is probably due to the fact that I commented out the getInstance(seed) calls. Parikshit needs to fix this, either by creating the instance of Randomness with a seed, or by using the .setSeed(seed) method.

**Comment by mbudiu-vmw** [comment]
Why couldn't you use the constructor with an argument there?

**Comment by uwieder** [comment]
Because Parikshit creates the instance in one method (with a seed) and then uses it in another method, relying on the fact it's a singleton. I can try to figure out where exactly to instantiate the seeds but I think it is better Parikshit do that.

**Pull request merged**
